### ISSUE TITLE
Support other rename methods, e. g. git mv

### ISSUE THREAD

**Issue by robinkrahl** [marcusbuffett/pipe-rename#1]
I really like this approach for bulk renaming!  It would be nice to be able to use this with `git mv`.  Currently, I can call pipe-rename and then `git add -A`, but this only works if there are no unstaged changes.

What do you think about adding a `--rename-command` option so that I could call `ls * | renamer --rename-command "git mv"`?

**Comment by marcusbuffett** [comment]
I like it! Cool idea. I can take a crack at this in the next couple days, or feel free to submit a PR

**Comment by marcusbuffett** [comment]
This should be covered by ec1576a3aa6d69d922ef57e35d5145b2b9dd491f .
Ex: `ls | renamer --rename-command="git mv"` or `ls | renamer -c="git mv"`

**Comment by robinkrahl** [comment]
Nice, thank you!  I think this might cause some issues with strange file
names (e. g. starting with -), but I’ll double-check that.

**Comment by marcusbuffett** [comment]
Ah I think you're right, the files should be passed as args probably instead, or escaped in some way
