### ISSUE TITLE
Allow to re-edit on confirmation step

### ISSUE THREAD

**Issue by bew** [marcusbuffett/pipe-rename#17]
Imagine you make some changes, and at the confirmation step you realise you made a mistake.

It would be nice to be able to add more actions than yes/no like:
- edit (re-open the tmp file to continue edit)
- restart/reset (discard the tmp file and make a new one)

What do you think of this?

**Comment by marcusbuffett** [comment]
I think this is a great idea, would definitely accept a PR w/ this, or I can get around to it at one point

**Comment by bew** [comment]
I guess this can be closed now, thanks @mtimkovich for the impl!
I wanted to do it as well but was virtually block by the method to use to select from multiple choices.. 👍
