### ISSUE TITLE
Alternative diff mode for confirmation

### ISSUE THREAD

**Issue by bew** [marcusbuffett/pipe-rename#18]
On the confirmation step, the output can be difficult to read, to see the real differences:
- when the terminal width is (too) small
- when the file names are long
- when the changes are small

I'm suggesting the use of another way to show the changes, similar to a git diff (with potential nice colors to highlight the changes), so instead of the current `old_file -> new_file` we could have:
- `plain diff mode`:
  ```
  - old_file
  + new_file

  - old_other_file
  + new_other_file
  ```

  like this:
  ![rename-plain](https://user-images.githubusercontent.com/9730330/107857822-1df54c00-6e31-11eb-8d28-dca9c57aebba.png)

- `smart diff mode`: same as `plain diff mode` but with additional details on the changes (similar to [delta](https://github.com/dandavison/delta), maybe some things can be re-used there, or use the same algorithm as delta (or a simpler one!) for the diff details)

  like this:
  ![rename-hi](https://user-images.githubusercontent.com/9730330/107857947-bee40700-6e31-11eb-861b-fd5dada2dd7b.png)
  (and we could still add the -/+ like the plain mode, in case colors don't work for some reason)

What do you think about this?

**Comment by marcusbuffett** [comment]
I wouldn't personally use this, but I can see the use case for long files or small changes in file names. Not opposed to a new option w/ this sort of output, would require minimal changes.
