### ISSUE TITLE
Abort if the editor command is not successful

### ISSUE THREAD

**Issue by robinkrahl** [marcusbuffett/pipe-rename#28]
If the editor command is not successful (see [`ExistStatus::success`](https://doc.rust-lang.org/std/process/struct.ExitStatus.html#method.success)), the rename should be aborted.  Currently, the exit status is ignored which is not intuitive.

**Comment by marcusbuffett** [comment]
Agreed, this is the same behavior `git commit` has, makes sense to me :+1:

**Comment by mtimkovich** [comment]
we can close this issue 🎉
