### ISSUE TITLE
`cargo install` reports no `clap::Clap`

### ISSUE THREAD

**Issue by wtanksleyjr** [marcusbuffett/pipe-rename#40]
The first error (out of many pages, of course) is:

error[E0432]: unresolved import `clap::Clap`

I am a total noob, so don't want to make wrong guesses about how to fix this.

**Comment by marcusbuffett** [comment]
Hm gotcha, looking into this

**Comment by marcusbuffett** [comment]
Thanks for the report, seems like clap made some breaking changes, not surprising given that it's a beta version. This should be fixed now.

**Comment by JacobTravers** [comment]
this seems to still be broken would you mind taking another look?

**Comment by marcusbuffett** [comment]
Yup just fixed 👍 forgot to publish changes

**Comment by JacobTravers** [comment]
Awesome thank you very much! this is a great tool, I use it daily and I forgot how convenient it was until I was unable to install it on a different machine lol

**Comment by wtanksleyjr** [comment]
Confirmed that the new version builds, thank you!

(Sorry I didn't report it, I assumed you had a release planned and I just
needed to check back this weekend.)

-Wm

**Comment by marcusbuffett** [comment]
Awesome thanks for confirming guys, happy to hear it’s useful
