### ISSUE TITLE
error[E0599] no function or associated item named `parse` found for struct `Opts` main.rs

### ISSUE THREAD

**Issue by JacobTravers** [marcusbuffett/pipe-rename#41]
Along with #40, I received the following error when trying
`cargo install pipe-rename`
```rust
error[E0599]: no function or associated item named `parse` found for struct `Opts` in the current scope
   --> /home/sugimoto/build/cargo/registry/src/github.com-1ecc6299db9ec823/pipe-rename-1.4.0/src/main.rs:317:22
    |
33  | struct Opts {
    | ----------- function or associated item `parse` not found for this
...
317 |     let opts = Opts::parse();
    |                      ^^^^^ function or associated item not found in `Opts`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `parse`, perhaps you need to implement it:
            candidate #1: `Parser`
```
Not sure if it is related, but I figured I should file an issue just in case.

**Comment by marcusbuffett** [comment]
Ah good to know, hadn't realized it broke the published package too. This should be fixed now, let me know if still having issues.

**Comment by JacobTravers** [comment]
Hey i was trying to use pipe-rename on my laptop and it looks like this issue has cropped up again

**Comment by marcusbuffett** [comment]
Oof, thanks for letting me know, this should be fixed again, for good this time since I'm not on a release candidate version anymore.
