### ISSUE TITLE
Create missing directories?

### ISSUE THREAD

**Issue by bew** [marcusbuffett/pipe-rename#50]
Hello!
Today I tried to do the following replacement:
![image](https://user-images.githubusercontent.com/9730330/172192428-43b13ed6-47c4-4efe-845a-743c79cea3c4.png)

I think it would be a great addition :)

**Comment by assarbad** [comment]
This is technically a duplicate of #43, no?

**Comment by bew** [comment]
totally :eyes:
thanks!
