### ISSUE TITLE
About tagging the releases

### ISSUE THREAD

**Issue by chenrui333** [marcusbuffett/pipe-rename#52]
👋 it would be good to create the release tags so that the downstream package managers can help with distributing the artifacts. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/105108

cc @marcusbuffett

**Comment by marcusbuffett** [comment]
Created a release tag for the latest release. Let me know if there's more to this, haven't done this before.

**Comment by chenrui333** [comment]
Thanks for the release tags, works for us (homebrew)!!
