### ISSUE TITLE
About 1.6.5 release

### ISSUE THREAD

**Issue by chenrui333** [marcusbuffett/pipe-rename#74]
👋 while [upgrading rust to 1.71.0](https://github.com/Homebrew/homebrew-core/pull/136514), we found that pipe-rename 1.6.5 checksum got changed, raise this issue to confirm if there was a re-reg for the 1.6.5 release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/137182

**Comment by mtimkovich** [comment]
Yeah sorry about that. It was a re-reg.

I tweaked some binary release flags (https://github.com/marcusbuffett/pipe-rename/commit/7027a2f11d1a1cce597a635db2f6d06956dcef96) which changed the checksum, but the code stayed the same so I didn't give it a new version number.

**Comment by chenrui333** [comment]
Cool, thanks for confirming it!
