### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by subnut** [marcusbuffett/pipe-rename#80]
According to `Cargo.toml`, this project is under the MIT license -
https://github.com/marcusbuffett/pipe-rename/blob/4bad1bd306362f22061c9f033844a523b7f0e6af/Cargo.toml#L10

<br/>

<br/>

<br/>

<br/>

But where is the license text?

**Comment by mtimkovich** [comment]
833bd82800ba772e30b495f65ad073c6f5305c82
