### ISSUE TITLE
Also accept files as positional arguments

### ISSUE THREAD

**Issue by robinkrahl** [marcusbuffett/pipe-rename#9]
I think it would be more intuitive if I could call `renamer *.txt` instead of `ls -l | renamer`.  My suggestion would be to use the positional arguments as input per default and only check stdin if there are no positional arguments.  What do you think?

**Comment by marcusbuffett** [comment]
I think this makes a lot of sense, seems like a common pattern in cli tools

**Comment by marcusbuffett** [comment]
Added in 2630dc533bf5d7588a807d63fa83f48a9fd4c851
